[package]
name = "runtime"
version.workspace = true
edition.workspace = true

[dependencies]
bytes = "1.10.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["full"] }
